//! The domain vocabulary, validated app-side at every write boundary (WI #526).
//!
//! These sets used to live in four places at once: Rust consts, DB CHECK
//! constraints and enum casts, hand-written MCP JSON schemas, and TypeScript
//! const-tuples. The DB copies were doing the enforcing, which meant a typo'd
//! t-shirt size or card status came back as a 500 with raw Postgres text.
//! korg-core is now the authority; the DB constraints are a backstop.
//!
//! `wi_type` was entirely free text before this (D-2). The vocabulary is the
//! union of what the live corpus actually uses plus `chore`, so nothing
//! existing is invalidated.

use crate::error::RepoError;

/// Canonical work-item statuses (WI #285). Lifecycle: `open → resolved`
/// (implemented; may still need a user test / may not be PR'd) `→ done`
/// (agent satisfied — terminal but still visible in default lists)
/// `→ closed` (Ken only; hidden by default).
pub const WI_STATUSES: [&str; 4] = ["open", "resolved", "done", "closed"];

/// Work-item types (D-2). `brainstorm` is deliberate: half-formed ideas get
/// filed as work items rather than lost.
pub const WI_TYPES: [&str; 7] = [
    "task",
    "bug",
    "chore",
    "feature",
    "research",
    "tweak",
    "brainstorm",
];

/// T-shirt sizes; mirrors the `wi_tshirt` CHECK in migration 0001.
pub const WI_TSHIRTS: [&str; 7] = ["XS", "S", "M", "L", "XL", "Huge", "Unknown"];

/// Kanban columns; mirrors the `card_status` enum in migration 0001.
pub const CARD_STATUSES: [&str; 6] = ["Backlog", "Research", "OnDeck", "Active", "Done", "Cut"];

/// Reading-list dispositions; mirrors the `link_disposition` enum (0004).
pub const LINK_DISPOSITIONS: [&str; 5] = ["Unread", "Done", "Revisit", "Summarized", "VaultSaved"];

/// Sprint-proposal lifecycle; mirrors `sprint_proposal_status` (0008).
pub const PROPOSAL_STATUSES: [&str; 4] = ["proposed", "active", "done", "declined"];

/// Daily-report statuses; mirrors the `report.status` CHECK (0010).
pub const REPORT_STATUSES: [&str; 3] = ["ok", "attention", "problem"];

/// Project lifecycle statuses (WI #246). Default WI-page rail shows only
/// `active` + `maintenance` unless "show all" is on.
pub const PROJECT_STATUSES: [&str; 4] = ["active", "maintenance", "inactive", "archived"];

/// Every vocabulary, as `(const name, TypeScript type name, values)`. Adding a
/// set here is all it takes for the web app to see it: `just gen` writes them
/// into `web/src/lib/generated/vocab.ts`, so the UI's status lists stop being a
/// hand-kept copy that drifts (the old `api.ts` `WI_TYPES` had nine entries,
/// six of which the server rejects).
#[cfg(test)]
const EXPORTED: [(&str, &str, &[&str]); 9] = [
    ("WI_STATUSES", "WiStatus", &WI_STATUSES),
    ("WI_TYPES", "WiType", &WI_TYPES),
    ("WI_TSHIRTS", "WiTshirt", &WI_TSHIRTS),
    ("CARD_STATUSES", "CardStatus", &CARD_STATUSES),
    ("LINK_DISPOSITIONS", "Disposition", &LINK_DISPOSITIONS),
    ("PROPOSAL_STATUSES", "ProposalStatus", &PROPOSAL_STATUSES),
    ("REPORT_STATUSES", "ReportStatus", &REPORT_STATUSES),
    ("PROJECT_STATUSES", "ProjectStatus", &PROJECT_STATUSES),
    // Not a domain vocabulary but the same kind of fact: a closed set the
    // client must agree with. The web app branches on it to tell "you typed
    // something wrong" from "korg broke" (sprint 019).
    ("ERROR_CODES", "ErrorCode", &crate::error::ERROR_CODES),
];

/// Reject a value outside its vocabulary with the full allowed set in the
/// message — the error doubles as the documentation an agent needs to retry.
pub fn validate(value: &str, allowed: &[&str], what: &str) -> Result<(), RepoError> {
    if allowed.contains(&value) {
        Ok(())
    } else {
        Err(RepoError::InvalidInput(format!(
            "invalid {what} '{value}' — expected one of: {}",
            allowed.join(", ")
        )))
    }
}

/// Emit the vocabularies — and the relationship-label registry — as
/// TypeScript, next to the `ts-rs` output (WI #541).
///
/// This runs as a test because that is where `ts-rs` generates too, so one
/// `just gen` invocation produces the whole `web/src/lib/generated/` directory
/// and CI's `git diff --exit-code` covers all of it. Naming it
/// `export_bindings_*` puts it in the same `cargo test export_bindings` filter
/// `ts-rs` uses.
#[cfg(test)]
mod generate {
    use super::EXPORTED;
    use crate::relationships::REGISTRY;

    fn quoted(values: &[&str]) -> String {
        values
            .iter()
            .map(|v| format!("\"{v}\""))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn render() -> String {
        let mut out = String::from(
            "// This file is generated by `just gen` from korg-core. Do not edit this file manually.\n",
        );
        for (name, ty, values) in EXPORTED {
            out.push_str(&format!(
                "\nexport const {name} = [{}] as const;\nexport type {ty} = (typeof {name})[number];\n",
                quoted(values)
            ));
        }
        out.push_str(
            "\n/** The relationship labels korg itself writes or interprets. Any other\n \
             *  label is legal and its direction is caller-defined. */\nexport const \
             RELATIONSHIP_LABELS = [\n",
        );
        for spec in REGISTRY {
            out.push_str(&format!(
                "  {{ label: \"{}\", directed: {}, reads: \"{}\" }},\n",
                spec.label, spec.directed, spec.reads
            ));
        }
        out.push_str("] as const;\nexport type RelationshipLabel = (typeof RELATIONSHIP_LABELS)[number][\"label\"];\n");
        out
    }

    #[test]
    fn export_bindings_vocab() {
        let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "./bindings".into());
        std::fs::create_dir_all(&dir).expect("create export dir");
        std::fs::write(std::path::Path::new(&dir).join("vocab.ts"), render())
            .expect("write vocab.ts");
    }
}
